//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeremyTCD.PipelinesCE.CommandLineApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeremyTCD.PipelinesCE.CommandLineApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipelinesCE, a continuous everything tool..
        /// </summary>
        public static string CommandDescription_Root {
            get {
                return ResourceManager.GetString("CommandDescription_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs a Pipeline.
        /// </summary>
        public static string CommandDescription_Run {
            get {
                return ResourceManager.GetString("CommandDescription_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipelinesCE.
        /// </summary>
        public static string CommandFullName_Root {
            get {
                return ResourceManager.GetString("CommandFullName_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string CommandFullName_Run {
            get {
                return ResourceManager.GetString("CommandFullName_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipelinesce.
        /// </summary>
        public static string CommandName_Root {
            get {
                return ResourceManager.GetString("CommandName_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run.
        /// </summary>
        public static string CommandName_Run {
            get {
                return ResourceManager.GetString("CommandName_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string HelpOptionSymbolName {
            get {
                return ResourceManager.GetString("HelpOptionSymbolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0} Command with arguments:
        ///{1}.
        /// </summary>
        public static string Log_RunningCommand {
            get {
                return ResourceManager.GetString("Log_RunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running command line application with arguments: [{0}].
        /// </summary>
        public static string Log_RunningCommandLineApp {
            get {
                return ResourceManager.GetString("Log_RunningCommandLineApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output verbose logs and build config project in debug configuration.
        /// </summary>
        public static string OptionDescription_Debug {
            get {
                return ResourceManager.GetString("OptionDescription_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build config project in release configuration.
        /// </summary>
        public static string OptionDescription_DebugOff {
            get {
                return ResourceManager.GetString("OptionDescription_DebugOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Pipeline in dry run mode.
        /// </summary>
        public static string OptionDescription_DryRun {
            get {
                return ResourceManager.GetString("OptionDescription_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Pipeline in normal mode.
        /// </summary>
        public static string OptionDescription_DryRunOff {
            get {
                return ResourceManager.GetString("OptionDescription_DryRunOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables file logging. Logs will be written to a log file named &quot;PipelinesCE.log&quot;. This log file will be located in the same directory as the target project..
        /// </summary>
        public static string OptionDescription_FileLogging {
            get {
                return ResourceManager.GetString("OptionDescription_FileLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables file logging..
        /// </summary>
        public static string OptionDescription_FileLoggingOff {
            get {
                return ResourceManager.GetString("OptionDescription_FileLoggingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file. Can be an absolute path, a relative path or a file name. If a relative path is provided, it is resolved relative to the target project&apos;s directory. If a file name is provided, the file will be located in the same directory as the target project. .
        /// </summary>
        public static string OptionDescription_LogFile {
            get {
                return ResourceManager.GetString("OptionDescription_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the pipeline to run. By convention, a Pipeline&apos;s name is its PipelineFactorys name less &quot;PipelineFactory&quot;. For example, &quot;MainPipelineFactory&quot; produces a Pipeline named &quot;Main&quot;. If this option is ommitted and only one Pipeline has been defined, PipelinesCE will run the lone Pipeline..
        /// </summary>
        public static string OptionDescription_Pipeline {
            get {
                return ResourceManager.GetString("OptionDescription_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or path of the PipelinesCE config project file to use. If a name is provided,  the file is located via a recursive search in the current directory. If a relative path is provided, the path is considered relative to current directory. The default value of this option is &quot;PipelinesCE.csproj&quot;..
        /// </summary>
        public static string OptionDescription_ProjectFile {
            get {
                return ResourceManager.GetString("OptionDescription_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output verbose logs.
        /// </summary>
        public static string OptionDescription_Verbose {
            get {
                return ResourceManager.GetString("OptionDescription_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output normal logs.
        /// </summary>
        public static string OptionDescription_VerboseOff {
            get {
                return ResourceManager.GetString("OptionDescription_VerboseOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debug.
        /// </summary>
        public static string OptionLongName_Debug {
            get {
                return ResourceManager.GetString("OptionLongName_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debugoff.
        /// </summary>
        public static string OptionLongName_DebugOff {
            get {
                return ResourceManager.GetString("OptionLongName_DebugOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dryrun.
        /// </summary>
        public static string OptionLongName_DryRun {
            get {
                return ResourceManager.GetString("OptionLongName_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dryrunoff.
        /// </summary>
        public static string OptionLongName_DryRunOff {
            get {
                return ResourceManager.GetString("OptionLongName_DryRunOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filelogging.
        /// </summary>
        public static string OptionLongName_FileLogging {
            get {
                return ResourceManager.GetString("OptionLongName_FileLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileloggingoff.
        /// </summary>
        public static string OptionLongName_FileLoggingOff {
            get {
                return ResourceManager.GetString("OptionLongName_FileLoggingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string OptionLongName_Help {
            get {
                return ResourceManager.GetString("OptionLongName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logfile.
        /// </summary>
        public static string OptionLongName_LogFile {
            get {
                return ResourceManager.GetString("OptionLongName_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipeline.
        /// </summary>
        public static string OptionLongName_Pipeline {
            get {
                return ResourceManager.GetString("OptionLongName_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectfile.
        /// </summary>
        public static string OptionLongName_ProjectFile {
            get {
                return ResourceManager.GetString("OptionLongName_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verbose.
        /// </summary>
        public static string OptionLongName_Verbose {
            get {
                return ResourceManager.GetString("OptionLongName_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verboseoff.
        /// </summary>
        public static string OptionLongName_VerboseOff {
            get {
                return ResourceManager.GetString("OptionLongName_VerboseOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string OptionLongName_Version {
            get {
                return ResourceManager.GetString("OptionLongName_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to db.
        /// </summary>
        public static string OptionShortName_Debug {
            get {
                return ResourceManager.GetString("OptionShortName_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string OptionShortName_DebugOff {
            get {
                return ResourceManager.GetString("OptionShortName_DebugOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dr.
        /// </summary>
        public static string OptionShortName_DryRun {
            get {
                return ResourceManager.GetString("OptionShortName_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dro.
        /// </summary>
        public static string OptionShortName_DryRunOff {
            get {
                return ResourceManager.GetString("OptionShortName_DryRunOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fl.
        /// </summary>
        public static string OptionShortName_FileLogging {
            get {
                return ResourceManager.GetString("OptionShortName_FileLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flo.
        /// </summary>
        public static string OptionShortName_FileLoggingOff {
            get {
                return ResourceManager.GetString("OptionShortName_FileLoggingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string OptionShortName_Help {
            get {
                return ResourceManager.GetString("OptionShortName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lf.
        /// </summary>
        public static string OptionShortName_LogFile {
            get {
                return ResourceManager.GetString("OptionShortName_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string OptionShortName_Pipeline {
            get {
                return ResourceManager.GetString("OptionShortName_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pf.
        /// </summary>
        public static string OptionShortName_ProjectFile {
            get {
                return ResourceManager.GetString("OptionShortName_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb.
        /// </summary>
        public static string OptionShortName_Verbose {
            get {
                return ResourceManager.GetString("OptionShortName_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vo.
        /// </summary>
        public static string OptionShortName_VerboseOff {
            get {
                return ResourceManager.GetString("OptionShortName_VerboseOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string OptionShortName_Version {
            get {
                return ResourceManager.GetString("OptionShortName_Version", resourceCulture);
            }
        }
    }
}
