//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeremyTCD.PipelinesCE.CommandLineApp {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeremyTCD.PipelinesCE.CommandLineApp.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run pipeline in dry run mode.
        /// </summary>
        public static string DryRunDescription {
            get {
                return ResourceManager.GetString("DryRunDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dryrun.
        /// </summary>
        public static string DryRunOptionLongName {
            get {
                return ResourceManager.GetString("DryRunOptionLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string DryRunOptionShortName {
            get {
                return ResourceManager.GetString("DryRunOptionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpOptionLongName {
            get {
                return ResourceManager.GetString("HelpOptionLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string HelpOptionShortName {
            get {
                return ResourceManager.GetString("HelpOptionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string HelpOptionSymbolName {
            get {
                return ResourceManager.GetString("HelpOptionSymbolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the pipeline to run. By convention, a pipeline&apos;s name is its factories name less &quot;PipelineFactory&quot;. For example, &quot;MainPipelineFactory&quot; produces a pipeline named &quot;Main&quot;. If this option is ommitted and only one pipeline has been defined, PipelinesCE will run the lone pipeline..
        /// </summary>
        public static string PipelineOptionDescription {
            get {
                return ResourceManager.GetString("PipelineOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipeline.
        /// </summary>
        public static string PipelineOptionLongName {
            get {
                return ResourceManager.GetString("PipelineOptionLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string PipelineOptionShortName {
            get {
                return ResourceManager.GetString("PipelineOptionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or path of the PipelinesCE project file to use. If a name is provided, PipelinesCE locates the file via a recursive search in the current directory. If this option is ommitted, PipelinesCE recursively searches for &quot;PipelinesCE.csproj&quot; in the current directory..
        /// </summary>
        public static string ProjectOptionDescription {
            get {
                return ResourceManager.GetString("ProjectOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project.
        /// </summary>
        public static string ProjectOptionLongName {
            get {
                return ResourceManager.GetString("ProjectOptionLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pj.
        /// </summary>
        public static string ProjectOptionShortName {
            get {
                return ResourceManager.GetString("ProjectOptionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PipelinesCE, a continuous everything tool..
        /// </summary>
        public static string RootCommandDescription {
            get {
                return ResourceManager.GetString("RootCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs a pipeline.
        /// </summary>
        public static string RunCommandDescription {
            get {
                return ResourceManager.GetString("RunCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write verbose output to console.
        /// </summary>
        public static string VerboseOptionDescription {
            get {
                return ResourceManager.GetString("VerboseOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verbose.
        /// </summary>
        public static string VerboseOptionLongName {
            get {
                return ResourceManager.GetString("VerboseOptionLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb.
        /// </summary>
        public static string VerboseOptionShortName {
            get {
                return ResourceManager.GetString("VerboseOptionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string VersionOptionLongName {
            get {
                return ResourceManager.GetString("VersionOptionLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string VersionOptionShortName {
            get {
                return ResourceManager.GetString("VersionOptionShortName", resourceCulture);
            }
        }
    }
}
